// <auto-generated />
namespace Delightful.Dal.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class ajoutdestablessecurity : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ajoutdestablessecurity));
        
        string IMigrationMetadata.Id
        {
            get { return "201409171453291_ajoutdestablessecurity"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
